name: Generate tests

on:
  repository_dispatch:
    types: [gen-test]
  workflow_dispatch:

jobs:
  generate_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out test-generator repo
        uses: actions/checkout@v4
        with:
          repository: empirical-run/test-generator
          ref: 1ea065e8a32aa035e1368e59639456f5bd54e797
          token: ${{ secrets.PAT }}
          path: .github/test-gen-repo

      - id: foo
        uses: ./.github/test-gen-repo/actions/gen-test
        with:
          secrets-pat: ${{ secrets.PAT }}
          secrets-openai: ${{ secrets.OPENAI_API_KEY }}
