name: Generate tests

on:
  repository_dispatch:
    types: [gen-test]
  workflow_dispatch:

jobs:
  generate_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out test-generator repo
        uses: actions/checkout@v4
        with:
          repository: empirical-run/test-generator
          ref: main
          token: ${{ secrets.PAT }}
          path: .github/test-gen-repo

      - uses: ./.github/test-gen-repo/actions/generate-test
        with:
          PAT: ${{ secrets.PAT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
