name: Generate tests

on:
  repository_dispatch:
    types: [gen-test]
  workflow_dispatch:

jobs:
  generate_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out test-generator repo
        uses: actions/checkout@v4
        with:
          repository: empirical-run/test-generator
          ref: test-run-publishes
          token: ${{ secrets.PAT }}
          path: .github/test-gen-repo

      - uses: ./.github/test-gen-repo/actions/generate-test
        with:
          PAT: ${{ secrets.PAT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DASHBOARD_DOMAIN: ${{ secrets.DASHBOARD_DOMAIN }}
