name: Generate tests

on:
  repository_dispatch:
    types: [gen-test]
  workflow_dispatch:

jobs:
  generate_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Actions Repo
        uses: actions/checkout@v4
        with:
          repository: empirical-run/test-generator
          ref: fa71be3496ee658ab81243d79c39ae9df80a8b66
          token: ${{ secrets.PAT }}
          path: .github/test-gen-repo

      - id: foo
        uses: ./.github/test-gen-repo/actions/gen-test
        with:
          secrets-pat: ${{ secrets.PAT }}
          secrets-openai: ${{ secrets.OPENAI_API_KEY }}
