name: Generate tests

on:
  repository_dispatch:
    types: [gen-test]
  workflow_dispatch:

jobs:
  generate_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out test-generator repo
        uses: actions/checkout@v4
        with:
          repository: empirical-run/test-generator
          ref: test-new-reporter-test-case-id
          token: ${{ github.event.client_payload.ghAppToken }}
          path: .github/test-gen-repo

      - uses: ./.github/test-gen-repo/actions/generate-test
        with:
          PAT: ${{ github.event.client_payload.ghAppToken }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
