name: Run Playwright tests

on:
  workflow_dispatch:
  repository_dispatch:
    types: [run-tests]
  push:
    branches: main
    paths:
      - "tests/**"
  pull_request:
    branches: main
    paths:
      - "tests/**"
      - ".github/workflows/run-tests.yml"

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out test-generator repo
        uses: actions/checkout@v4
        with:
          repository: empirical-run/test-generator
          token: ${{ secrets.PAT }}
          ref: fix/test-new-reporter
          path: .github/test-gen-repo

      - uses: ./.github/test-gen-repo/actions/run-tests
        with:
          PROJECT_NAME: flash
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
