name: Run Playwright tests

on:
  workflow_dispatch:
  repository_dispatch:
    types: [run-tests]
  push:
    branches: main
    paths:
      - "tests/**"
  pull_request:
    branches: main
    # paths:
    #   - "tests/**"
    #   - "playwright.config.ts"
    #   - ".github/workflows/run-tests.yml"

concurrency:
  group: "flash-tests"

jobs:
  run_tests:
    runs-on: warp-ubuntu-latest-arm64-8x
    steps:
      - name: Check out test-generator repo
        uses: actions/checkout@v4
        with:
          repository: empirical-run/test-generator
          token: ${{ secrets.PAT }}
          ref: ad-hoc-run-project-wildcard
          path: .github/test-gen-repo

      - uses: ./.github/test-gen-repo/actions/run-tests
        with:
          TEST_RUN_ENVIRONMENT: production
          PROJECT_NAME: flash
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
